name: Publish to Dev.to

on:
  push:
    branches: [main]
    paths:
      - 'content/posts/**'  # Only trigger when blog posts change
  workflow_dispatch:  # Allow manual triggering

jobs:
  publish-to-devto:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'letanure'  # Only run on your repo
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Download published posts tracking
        continue-on-error: true  # Don't fail if file doesn't exist
        uses: actions/download-artifact@v4
        with:
          name: published-posts
          path: .
          
      - name: Publish new posts to Dev.to
        env:
          DEVTO_API_KEY: ${{ secrets.DEVTO_API_KEY }}
        run: npm run publish:devto
        
      - name: Upload published posts tracking
        uses: actions/upload-artifact@v4
        with:
          name: published-posts
          path: published-posts.json
          retention-days: 365